# Generated by Django 4.2.1 on 2023-05-21 01:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('author_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for users', primary_key=True, serialize=False)),
                ('user_name', models.CharField(help_text='Choose a unique username', max_length=50, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('join_date', models.DateField(auto_now=True)),
                ('job', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
            ],
            options={
                'ordering': ['user_name', 'job'],
            },
        ),
        migrations.CreateModel(
            name='Codes',
            fields=[
                ('code_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Write a brief name for the code', max_length=255)),
                ('language', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('description', models.TextField(help_text='Write a small but usefull description for you and other user understanding')),
                ('timestamp', models.DateField(auto_now=True)),
                ('author_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.authors')),
            ],
        ),
    ]
